# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f8cc0001a1a388b1a5ae909ea9aa502d6eb99d7ac7de6b7d21fe3edb55661b32a0dfedba6b4946349d48b90a29c51dc8e84a36dcde8124763cff601d1a8edcd
  better_doctor_access_key: 4446a8c6b43d4c7c3898ca1e56f52325

test:
  secret_key_base: d7590ec651de3594a52c3d9479a7bb94c100b98b1385e177b29823d84b211a37394773e3aea8715c7dd778d7b10a991a7c0872a79c6ead5331b7a6f6efe65934
  better_doctor_access_key: 4446a8c6b43d4c7c3898ca1e56f52325

# Do not keep production secrets in the repository,
# instead read values from the environment.
# Need to move access_key to production nodes environment file
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  better_doctor_access_key: 4446a8c6b43d4c7c3898ca1e56f52325
